CREATE DATABASE IF NOT EXISTS hashtag_battle;

CREATE TABLE IF NOT EXISTS `battles`(
  `id` VARCHAR(30) NOT NULL,
  `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8

CREATE TABLE IF NOT EXISTS `hashtags`(
  `id` int NOT NULL AUTO_INCREMENT,
  `hashtag` VARCHAR(255) NOT NULL,
  `last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8

CREATE TABLE IF NOT EXISTS `hashtags_battles`(
	`battle_id` VARCHAR(30) NOT NULL,
	`hashtag_id` int NOT NULL
) ENGINE=MyISAM  DEFAULT CHARSET=utf8